#include <conio.h>
#include <iostream.h>

main()
{
    cout<<" *************halo BSI************"<<endl;
    cout<<" ============== .. ==========="<<endl;
    cout<<" +++++++++++SELAMAT DATANG MAHASISWAKU+++++++++++"<<endl;
    cout<<" nama       : verlinton simangunsong"<<endl;
    cout<<" kelompok   : 1 is the bets"<<endl;
    cout<<" no hp.     : 081280166292"<<endl;
    cout<<" alamat     : kp.rumpaksinang kel.pakulonan barat"<<endl;
    cout<<" status     : lajang"<<endl;
    cout<<" agama      : kristen";
    getch();
}
