/*-------------*/
/*inisilisasi array dimensi 1*/
/*-------------*/
#include <conio.h>
#include <iostream.h>

main()
{

 char hari[7][10]=
 {"minggu","senin","selasa","rabu","kamis","jumat","sabtu"};
 clrscr();
 cout<<"nama-nama hari:"<<endl;
 cout<<hari[0]<<endl<<hari[1]<<endl<<hari[2]<<endl<<hari[3]
 <<endl<<hari[4]<<endl<<hari[5]<<endl<<hari[6]<<endl<<hari[7]<<endl;
 getch();
 }


